version: "3.9"

services:
  web:
    build: .
    command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    expose:
      - "8000"

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A bookstore worker -l info
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A bookstore beat -l info
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web